# Generated by Django 5.1.2 on 2024-11-26 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_menu', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveIntegerField()),
                ('disposal_quantity', models.PositiveIntegerField(default=1)),
                ('disposal_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('disposal_notes', models.TextField(blank=True, help_text='任意の情報を追加できます', null=True)),
                ('disposal_registrant', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
