# Generated by Django 5.1.2 on 2025-01-20 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0001_initial'),
        ('menu', '0006_alter_product_id_alter_productingredient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposal',
            name='disposal_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
        ),
    ]
