# Generated by Django 5.1.2 on 2025-01-20 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0002_alter_disposal_disposal_menu'),
        ('menu', '0006_alter_product_id_alter_productingredient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposal',
            name='disposal_menu',
        ),
        migrations.AddField(
            model_name='disposal',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='menu.product'),
        ),
    ]
