# Generated by Django 5.1.2 on 2025-01-20 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0003_remove_disposal_disposal_menu_disposal_product'),
        ('menu', '0006_alter_product_id_alter_productingredient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposal',
            name='product',
        ),
        migrations.AddField(
            model_name='disposal',
            name='disposal_menu',
            field=models.CharField(default='未設定', max_length=255),
        ),
        migrations.CreateModel(
            name='DisposalIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product')),
                ('disposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='disposal.disposal')),
            ],
        ),
    ]
