# Generated by Django 5.1.2 on 2025-01-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0004_remove_disposal_product_disposal_disposal_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposalingredient',
            old_name='Product',
            new_name='product',
        ),
    ]
