# Generated by Django 5.1.2 on 2025-01-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0006_alter_disposal_disposal_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposal',
            name='disposal_menu',
            field=models.CharField(max_length=255),
        ),
    ]
