# Generated by Django 5.1.2 on 2025-01-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0009_alter_disposal_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisposalIngredient',
        ),
    ]
