# Generated by Django 5.1.2 on 2024-10-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食品名')),
                ('category', models.CharField(default='未分類', max_length=50, verbose_name='種類')),
                ('cost', models.PositiveIntegerField(verbose_name='原価')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('delivery_days', models.PositiveIntegerField(verbose_name='納期（日数）')),
                ('expiration_date', models.DateField(verbose_name='賞味・消費期限')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
            ],
        ),
    ]
