# Generated by Django 5.1.2 on 2024-10-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='delivery_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
