# Generated by Django 5.1.2 on 2024-11-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDatetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('work_start_time', models.DateTimeField(blank=True, null=True)),
                ('work_end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
