# Generated by Django 5.1.2 on 2024-11-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_product_store_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, help_text='任意の情報を追加できます', null=True),
        ),
    ]
